import { useState } from 'react';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { Select } from '../components/ui/Select';
import { formatMoney } from '../utils/money';
import { toInputDate } from '../utils/dates';
export function ServiceEntryPage({ doctors, categories, entries, onCreate }) {
  const firstCategory = categories[0]; const firstService = firstCategory?.services?.[0];
  const [form, setForm] = useState({ entryDate: new Date().toISOString().slice(0,10), doctorId: doctors[0]?.id || '', categoryId: firstCategory?.id || '', serviceId: firstService?.id || '', quantity: 1 });
  const selectedCategory = categories.find((c) => c.id === Number(form.categoryId));
  const services = selectedCategory?.services || [];
  const selectedService = services.find((s) => s.id === Number(form.serviceId));
  function update(field, value) { const next = { ...form, [field]: value }; if (field === 'categoryId') next.serviceId = categories.find((c) => c.id === Number(value))?.services?.[0]?.id || ''; setForm(next); }
  return <div className="grid gap-6 xl:grid-cols-[420px_1fr]"><Card><div className="p-6"><h3 className="text-lg font-bold">Novi unos usluge</h3><p className="mt-1 text-sm text-slate-500">Cena se kopira iz cenovnika kao snapshot.</p><div className="mt-6 grid gap-4"><input type="date" value={form.entryDate} onChange={(e) => update('entryDate', e.target.value)} className="h-11 rounded-2xl border border-slate-200 px-4" /><Select value={form.doctorId} onChange={(v) => update('doctorId', v)}>{doctors.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</Select><Select value={form.categoryId} onChange={(v) => update('categoryId', v)}>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</Select><Select value={form.serviceId} onChange={(v) => update('serviceId', v)}>{services.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</Select><div className="grid grid-cols-2 gap-3"><input type="number" min="1" value={form.quantity} onChange={(e) => update('quantity', e.target.value)} className="h-11 rounded-2xl border border-slate-200 px-4" /><input readOnly value={formatMoney(selectedService?.currentPrice)} className="h-11 cursor-not-allowed rounded-2xl border border-slate-200 bg-slate-50 px-4 text-slate-500" /></div><Button onClick={() => onCreate(form)} className="h-11 rounded-2xl bg-sky-600 text-white">Dodaj uslugu</Button></div></div></Card><Card><div className="border-b border-slate-100 p-6"><h3 className="text-lg font-bold">Evidencija usluga</h3></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-6 py-4">Datum</th><th>Doktor</th><th>Kategorija</th><th>Usluga</th><th>Kol</th><th>Cena snapshot</th><th>Ukupno</th></tr></thead><tbody className="divide-y divide-slate-100">{entries.map((e) => <tr key={e.id}><td className="px-6 py-4">{toInputDate(e.entryDate)}</td><td>{e.doctor?.name}</td><td>{e.category?.name}</td><td>{e.service?.name}</td><td>{e.quantity}</td><td>{formatMoney(e.priceSnapshot)}</td><td className="font-bold">{formatMoney(Number(e.quantity) * Number(e.priceSnapshot))}</td></tr>)}</tbody></table></div></Card></div>;
}
